// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AlgebraProblemGenerator")>]
[<assembly: AssemblyProductAttribute("AlgebraProblemGenerator")>]
[<assembly: AssemblyDescriptionAttribute("Algebra problem generator based on Microsoft Research's paper: https://www.cse.iitk.ac.in/users/cs365/2013/hw2/singh-gulwani-12_automatically-generating-algebra-problems.pdf")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AlgebraProblemGenerator"
    let [<Literal>] AssemblyProduct = "AlgebraProblemGenerator"
    let [<Literal>] AssemblyDescription = "Algebra problem generator based on Microsoft Research's paper: https://www.cse.iitk.ac.in/users/cs365/2013/hw2/singh-gulwani-12_automatically-generating-algebra-problems.pdf"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
